name: CI/CD Pipeline for Team Microservice

on:
  push:
    branches:
      - main
      - dev
      - release
      - hotfix
      - feature/*
  pull_request:
    branches:
      - main
      - dev
      - release
      - hotfix
      - feature/*

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          query-suite: security-extended
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Build with Maven
        run: mvn clean install -DskipTests


      - name: Run Tests
        run: mvn test || true

      - name: Package build artifacts
        run: |
          mkdir -p artifact
          cp -r target/* artifact/
          zip -r build-artifact.zip artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.zip

     
